/** Declaration file generated by dts-gen */

export function createTransport(options: any): any;

export namespace mock {
    const shouldFailCheck: any;

    function failResponse(error: any): void;

    function getSentMail(): void;

    function mockedVerify(isMocked: any): void;

    function reset(): void;

    function sentMail(): void;

    function setFailResponse(error: any): void;

    function setMockedVerify(isMocked: any): void;

    function setShouldFail(isFail: any): void;

    function setShouldFailCheck(check: any): void;

    function setShouldFailOnce(): void;

    function setSuccessResponse(response: any): void;

    function shouldFail(isFail: any): void;

    function shouldFailOnce(): void;

    function successResponse(response: any): void;

}

